app/urls.py
from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('error_autenticar', views.error_autenticar, name='error_autenticar'), 
    path('autenticar/', views.autenticar, name='autenticar'),
    path('salir/', views.post_salir, name='post_salir'),

    path('crea_empresa/', views.crea_empresa, name='crea_empresa'),
    path('crea_empresa_post/', views.post_crea_empresa, name='post_crea_empresa'),

    path('estudiante/', views.estudiante, name='estudiante'),
    path('estudiante/lista_postulaciones/', views.lista_postulaciones, name='lista_postulaciones'),
    path('estudiante/consultar_postulacion/<int:postulacion_id>/', views.consultar_postulacion, name='consultar_postulacion'),
    path('estudiante/lista_convocatorias_abiertas/', views.lista_convocatorias_abiertas, name='lista_convocatorias_abiertas'),
    path('estudiante/consulta_convocatoria_abierta/<int:convocatoria_id>/', views.consulta_convocatoria_abierta, name='consulta_convocatoria_abierta'),
    path('estudiante/editar_perfil_estudiante/', views.editar_perfil_estudiante, name='editar_perfil_estudiante'),
    path('estudiante/editar_perfil_estudiante_post/', views.editar_perfil_estudiante_post, name='editar_perfil_estudiante_post'),
    path('estudiante/confirmar_postulacion/<int:convocatoria_id>/', views.confirmar_postulacion, name='confirmar_postulacion'),
    path('estudiante/confirmar_postulacion_post/<int:convocatoria_id>/', views.confirmar_postulacion_post, name='confirmar_postulacion_post'),
    path('estudiante/error_postulacion/', views.error_postulacion, name='error_postulacion'),
    
    path('empresa/', views.empresa, name='empresa'),
    path('empresa/crea_convocatoria/', views.crea_convocatoria, name='crea_convocatoria'),
    path('empresa/crea_convocatoria_post/', views.crea_convocatoria_post, name='crea_convocatoria_post'),
    path('empresa/lista_convocatoria/', views.lista_convocatoria, name='lista_convocatoria'),
    path('empresa/cerrar_convocatoria/<int:convocatoria_id>/', views.cerrar_convocatoria, name='cerrar_convocatoria'),
    path('empresa/cerrar_convocatoria_post/<int:convocatoria_id>/', views.cerrar_convocatoria_post, name='cerrar_convocatoria_post'),
    path('empresa/editar_convocatoria/<int:convocatoria_id>/', views.editar_convocatoria, name='editar_convocatoria'),
    path('empresa/editar_convocatoria_post/<int:convocatoria_id>/', views.editar_convocatoria_post, name='editar_convocatoria_post'),
    path('empresa/consulta_convocatoria/<int:convocatoria_id>/', views.consulta_convocatoria, name='consulta_convocatoria'),
    path('empresa/consulta_convocatoria/<int:convocatoria_id>/editar_postulacion/<int:postulacion_id>/', views.editar_postulacion, name='editar_postulacion'),
    path('empresa/consulta_convocatoria/<int:convocatoria_id>/editar_postulacion_post/<int:postulacion_id>/', views.editar_postulacion_post, name='editar_postulacion_post'),
    path('empresa/consulta_convocatoria/<int:convocatoria_id>/consulta_estudiante/<int:postulacion_id>/', views.consulta_estudiante, name='consulta_estudiante'),

    path('coordinador/', views.coordinador, name='coordinador'),
    path('coordinador/lista_empresas/', views.lista_empresas, name='lista_empresas'),
    path('coordinador/consultar_empresa/<int:empresa_id>/', views.consultar_empresa, name='consultar_empresa'),
    path('coordinador/lista_convocatorias_total/', views.lista_convocatorias_total, name='lista_convocatorias_total'),
    path('coordinador/consulta_convocatorias_total/<int:convocatoria_id>/', views.consulta_convocatorias_total, name='consulta_convocatorias_total'),
    path('coordinador/lista_estudiantes/', views.lista_estudiantes, name='lista_estudiantes'),
    path('coordinador/consultar_estudiante/<int:estudiante_id>/', views.consultar_estudiante, name='consultar_estudiante'),
    path('coordinador/crear_estudiante/', views.crear_estudiante, name='crear_estudiante'),
    path('coordinador/crear_estudiante_post/', views.crear_estudiante_post, name='crear_estudiante_post'),
    path('coordinador/consultar_historico/', views.consultar_historico, name='consultar_historico'),
    path('coordinador/actualizar_semestre/', views.actualizar_semestre, name='actualizar_semestre'),
    path('coordinador/actualizar_semestre_post/', views.actualizar_semestre_post, name='actualizar_semestre_post'),
]

nube_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/acceder_otro.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error postulacion</title>
    <link rel="stylesheet" href="{% static 'app/css/error_postulacion.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
</head>
<body>
    <input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <div class="left_area">
        <h3>Estudiante - {{request.user.username}}</h3>
      </div> 
      <div class="right_area">
        <a href="{% url 'app:post_salir' %}" class="logout_btn">Salir</a>
      </div>
    </header>
    <div class="sidebar">
    </div>
    <div class="content">
        <form class="form-crear">
            <div class="header">
                <h1>Postulacion existente</h1>
            </div>
            <div class="estado">
                <p>Ya se postulo a esta convocatoria</p>
                <a href="{% url 'app:lista_convocatorias_abiertas' %}">Regresar</a>
            </div>
        </form>
    </div>
</body>
</html>

app/templates/app/cerrar_convocatoria.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cuenta de empresa</title>
    <link rel="stylesheet" href="{% static 'app/css/confirmar_postulacion.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
</head>
<body>
    <!--header area start-->
    <header>
      <div class="left_area">
        <h3>Empresa - {{request.user.username}}</h3>
      </div> 
      <div class="right_area">
        <a href="{% url 'app:post_salir' %}" class="logout_btn">Salir</a>
      </div>
    </header>
    <div class="content">
        <div class="cuadro">
            <div class="header">
                <p>Esta seguro de cerrar la convocatoria?</p>
            </div>
            <div class="cuerpo">
                <form action="{% url 'app:cerrar_convocatoria_post' convocatoria.id %}" method="POST">
                <button type="submit" id="si">Si</button>
                <a href="{% url 'app:lista_convocatoria' %}" id="no">No</a>
                {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/app/consulta_convocatoria.html
{% extends 'app/layout_empresa.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'app/css/consultas.css' %}">
{% endblock %}
{% block contenido %}
{% if convocatoria %}
<h1>{{convocatoria.nombre}}</h1>
<hr>
<label for="fincial">Fecha Incial</label>
<h2>{{convocatoria.fecha_inicial}}</h2>
<label for="ffinal">Fecha Final</label>
<h2>{{convocatoria.fecha_final}}</h2>
<hr>
<label for="descripcion">Descripción</label>
<p>{{convocatoria.descripcion}}</p>
<hr>
<label for="estado">Estado</label>
{% if convocatoria.abierta is True %}
<h2>Cerrada</h2>
{% else %}
<h2>Abierta</h2>
{% endif %}
<hr>
<label for="lista" id="postulantes">Lista postulantes</label>
<table class="tabla_convocatorias">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th>Estado postulacion</th>
        {% if convocatoria.abierta is False %}
        <th>Editar</th>
        {% endif %}
        <th>Consultar</th>
      </tr>
    </thead>
    
    <tbody>
      {% for pos in postulaciones %}
      <tr>
        <td>{{pos.estudiante.user.first_name}} {{pos.estudiante.user.last_name}}</td>
        <td>{{pos.estudiante.user.email}}</td>
        {% if pos.aceptada is True %}
        <td>Aceptada</td>
        {% else %}
        <td>Rechazada</td>
        {% endif %}
        {% if convocatoria.abierta is False %}
        <td>
          <a href="{% url 'app:editar_postulacion' convocatoria.id pos.id %}">
              <i class="fas fa-edit"></i>
          </a>
        </td>
        {% endif %}
        <td>
          <a href="{% url 'app:consulta_estudiante' convocatoria.id pos.id %}">
              <i class="fas fa-search"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
      </tbody>
</table>
{% endif %}
{% endblock %}

app/templates/app/consulta_convocatoria_est.html
{% extends 'app/layout_estudiante.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'app/css/consultas.css' %}">
{% endblock %}
{% block contenido %}
{% if convocatoria %}
<h1>{{convocatoria.nombre}}</h1>
<hr>
<label for="fincial">Fecha Incial</label>
<h2>{{convocatoria.fecha_inicial}}</h2>
<label for="ffinal">Fecha Final</label>
<h2>{{convocatoria.fecha_final}}</h2>
<hr>
<label for="descripcion">Descripción</label>
<p>{{convocatoria.descripcion}}</p>
<hr>
<label for="estado">Estado</label>
{% if convocatoria.abierta is True %}
<h2>Cerrada</h2>
{% else %}
<h2>Abierta</h2>
{% endif %}
{% endif %}
{% endblock %}

app/templates/app/coordinador.html
{% extends 'app/layout_coordinador.html' %}
{% load static %}
{% block contenido %}
<div class="presentacion">
  <h1>Bienvenido al portal de coordinadores</h1>
</div>
<div class="imagen">
  <img src="{% static 'app/img/coordinador.jpg' %}" alt="">
</div>
<div class="card">
  <p>Este portal permite crear estudiantes y llevar el control de los estudiantes en las convocatorias.</p>
</div>
{% endblock %}

app/templates/app/crea_convocatoria.html
{% extends 'app/layout_empresa.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'app/css/crea_convocatoria.css' %}">
{% endblock %}
{% block contenido %}
<form class="form-crear" method="POST" action="{% url 'app:crea_convocatoria_post' %}">
  <div class="header">
      <h1>Crear convocatoria</h1>
  </div>
  <div class="nombre">
      <label for="name">Nombre</label><h5>*</h5>
      <br>
      <input type="text" id="name" name="name" required autofocus>
  </div>
  <div class="finicial">
      <label for="fecha_inicial">Fecha inicial</label><h5>*</h5>
      <br>
      <input type="date" id="fecha_inicial" name="fecha_inicial" required>
  </div>
  <div class="ffinal">
      <label for="fecha_final">Fecha final</label><h5>*</h5>
      <br>
      <input type="date" name="fecha_final" id="fecha_final" required>
  </div>
  <div class="desc">
      <label for="descripcion">Descripción</label>
      <br>
      <textarea name="descripcion" id="descripcion" rows="10" cols="50"></textarea>
  </div>
  <div class="crear">
      <button class="bt_crea_convocatoria" type="submit">
      Crear convocatoria</button>
  </div>
  {% csrf_token %}
</form>
{% endblock %}

app/templates/app/error_autenticacion.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error postulacion</title>
    <link rel="stylesheet" href="{% static 'app/css/error_postulacion.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
</head>
<body>
    <input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <div class="left_area">
        <h3>Error</h3>
      </div> 
      <div class="right_area">
      </div>
    </header>
    <div class="sidebar">
    </div>
    <div class="content">
        <form class="form-crear">
            <div class="header">
                <h1>Credenciales erroneas</h1>
            </div>
            <div class="estado">
                <p>¡No digito credenciales validas!</p>
                <a href="{% url 'app:index' %}">Regresar</a>
            </div>
        </form>
    </div>
</body>
</html>

app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/index.css' %}">
    <title>Inicio sesion</title>
</head>
<body>
    <div class="contenedor">
        <div class="parte1">
        </div>
        <div class="parte2">
            <form class="form-inicio" method="POST" action="{% url 'app:autenticar' %}">
                {% csrf_token %}
                <h1>Inicio de sesión</h1>
                <h5>*</h5>
                <input type="text" class="campo" placeholder="Username" required autofocus name="username">
                <h5>*</h5>
                <input type="password" class="campo" placeholder="Contraseña" required name="contra">
                <a href="#" class="olvido_contra">¿Olvidaste tu contraseña? </a> 
                <button class="bt_login" type="submit">
                    Siguiente</button>
            </form> 
        </div>
        <div class="parte3">
            <a href="{% url 'app:crea_empresa' %}" class="crea_empresa">Crear empresa</a> 
        </div>
    </div>
</body>
</html>

app/templates/app/layout_coordinador.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cuenta de coordinador</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'app/css/inicio.css' %}">
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
</head>
<body>
    <input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <label for="check">
        <i class="fas fa-bars" id="sidebar_btn"></i>
      </label>
      <div class="left_area">
        <h3>Coordinador - {{ request.user.username }}</h3>
      </div> 
      <div class="right_area">
        <a href="{% url 'app:actualizar_semestre' %}" class="btn_actualizar"><i class="fas fa-sync-alt"></i> Semestre</a>
        <a href="{% url 'app:post_salir' %}" class="logout_btn">Salir</a>
      </div>
    </header>
    <div class="sidebar">
        <a href="{% url 'app:coordinador' %}"><i class="fas fa-home"></i><span>Inicio</span></a>
      <a href="{% url 'app:lista_empresas' %}"><i class="fas fa-briefcase"></i><span>Lista de empresas</span></a>
      <a href="{% url 'app:lista_convocatorias_total' %}"><i class="fas fa-th-list"></i><span>Lista de convocatorias</span></a>
      <a href="{% url 'app:lista_estudiantes' %}"><i class="fas fa-user"></i><span>Perfiles estudiantes</span></a>
      <a href="{% url 'app:crear_estudiante' %}"><i class="fas fa-pen"></i><span>Crear estudiante</span></a>
      <a href="{% url 'app:consultar_historico' %}"><i class="fas fa-history"></i><span>Historico estudiantes</span></a>
    </div>
    <div class="content">
        {% block contenido %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/app/layout_empresa.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cuenta de empresa</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'app/css/inicio.css' %}">
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
</head>
<body>
    <input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <label for="check">
        <i class="fas fa-bars" id="sidebar_btn"></i>
      </label>
      <div class="left_area">
        <h3>Empresa - {{ request.user.username }}</h3>
      </div> 
      <div class="right_area">
        <a href="{% url 'app:post_salir' %}" class="logout_btn">Salir</a>
      </div>
    </header>
    <div class="sidebar">
      <a href="{% url 'app:empresa' %}"><i class="fas fa-home"></i><span>Inicio</span></a>
      <a href="{% url 'app:crea_convocatoria' %}"><i class="fas fa-pen"></i><span>Crear convocatoria</span></a>
      <a href="{% url 'app:lista_convocatoria' %}"><i class="fas fa-th-list"></i><span>Lista de convocatorias</span></a>
    </div>
    <div class="content">
        {% block contenido %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/app/layout_estudiante.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cuenta de estudiante</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'app/css/inicio.css' %}">
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
</head>
<body>
    <input type="checkbox" id="check">
    <!--header area start-->
    <header>
      <label for="check">
        <i class="fas fa-bars" id="sidebar_btn"></i>
      </label>
      <div class="left_area">
        <h3>Estudiante - {{ request.user.username }}</h3>
      </div> 
      <div class="right_area">
        <a href="{% url 'app:post_salir' %}" class="logout_btn">Salir</a>
      </div>
    </header>
    <div class="sidebar">
      <a href="{% url 'app:estudiante' %}"><i class="fas fa-home"></i><span>Inicio</span></a>
      <a href="{% url 'app:lista_postulaciones' %}"><i class="fas fa-file-contract"></i><span>Lista postulaciones</span></a>
      <a href="{% url 'app:lista_convocatorias_abiertas' %}"><i class="fas fa-th-list"></i><span>Lista de convocatorias</span></a>
      <a href="{% url 'app:editar_perfil_estudiante' %}"><i class="fas fa-user-edit"></i><span>Editar perfil</span></a>
    </div>
    <div class="content">
        {% block contenido %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/app/lista_convocatoria.html
{% extends 'app/layout_empresa.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'app/css/listas.css' %}">
{% endblock %}
{% block contenido %}
<h1><i class="fas fa-list-alt"></i> Lista de convocatorias</h1>
        <hr>
        <table class="tablas">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Fecha Incio</th>
                <th>Fecha final</th>
                <th>Postulaciones</th>
                <th>Estado</th>
                <th>Cerrar</th>
                <th>Editar</th>
                <th>Consultar</th>
              </tr>
            </thead>
            {% if convocatorias %}
            <tbody>
                {% for con in convocatorias %}
              <tr>
                <td>{{con.nombre}}</td>
                <td>{{con.fecha_inicial}}</td>
                <td>{{con.fecha_final}}</td>
                <td>{{con.postulaciones.count}}</td>
                {% if con.abierta is True %}
                <td id="Estado">Cerrada</td>
                {% else %}
                <td id="Estado">Abierta</td>
                {% endif %}
                {% if con.abierta is True %}
                <td><i class="fas fa-check-circle"></i></td>
                {% else %}
                <td>
                  <a href="{% url 'app:cerrar_convocatoria' con.id%}">
                    <i class="fas fa-times-circle"></i>
                  </a>
                </td>
                {% endif %}
                {% if con.postulaciones.count == 0 %}
                <td>
                    <a href="{% url 'app:editar_convocatoria' con.id%}">
                        <i class="fas fa-edit"></i>
                    </a>
                </td>
                {% else %}
                <td>No puede</td>
                {% endif %}
                <td>
                    <a href="{% url 'app:consulta_convocatoria' con.id %}">
                        <i class="fas fa-search"></i>
                    </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>  
            {% endif %}  
        </table>
{% endblock %}

app/templates/app/lista_convocatorias_abiertas.html
{% extends 'app/layout_estudiante.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'app/css/listas.css' %}">
{% endblock %}
{% block contenido %}
<h1><i class="fas fa-calendar-check"></i> Lista de convocatorias abiertas</h1>
        <hr>
        <table class="tablas">
            <thead>
              <tr>
                <th>Empresa</th>
                <th>Nombre convocatoria</th>
                <th>Fecha inicial</th>
                <th>Fecha final</th>
                <th>Postular</th>
                <th>Consultar</th>
              </tr>
            </thead>
            {% if convocatorias %}
            <tbody>
              {% for con in convocatorias %}
              <tr>
                <td>{{con.empresa.user.username}}</td>
                <td>{{con.nombre}}</td>
                <td>{{con.fecha_inicial}}</td>
                <td>{{con.fecha_final}}</td>
                <td>
                    <a href="{% url 'app:confirmar_postulacion' con.id %}">
                        <i class="far fa-check-circle"></i>
                    </a>
                </td>
                <td>
                  <a href="{% url 'app:consulta_convocatoria_abierta' con.id %}">
                    <i class="fas fa-search"></i>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
            {% endif %}
        </table>
{% endblock %}

app/templates/app/lista_empresas.html
{% extends 'app/layout_coordinador.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'app/css/listas.css' %}">
{% endblock %}
{% block contenido %}
<h1><i class="fas fa-briefcase"></i> Lista de empresas</h1>
<hr>
<table class="tablas">
    <thead>
      <tr>
        <th>Nombre empresa</th>
        <th>Ciudad</th>
        <th>Contacto</th>
        <th>Email</th>
        <th>Consultar</th>
      </tr>
    </thead>
    {% if lista_empresas %}
    <tbody>
      {% for em in lista_empresas %}
      <tr>
        <td>{{em.user.username}}</td>
        <td>{{em.ciudad}}</td>
        <td>{{em.nombre_contacto}}</td>
        <td>{{em.user.email}}</td>
        <td>
            <a href="{% url 'app:consultar_empresa' em.id%}">
                <i class="fas fa-search"></i>
            </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    {% endif %}
</table>
{% endblock %}